### ISSUE TITLE
API_interface.py

### ISSUE THREAD

**Issue by ghost** [jonp92/Milliner#1]
I'm surprised this worked :)
Are you having any issues with it?
Maybe I can help troubleshoot.

**Comment by jonp92** [comment]
I figured out the biggest hurdle which was generating PreAuthkeys. u/Reverent who is a Headscale-ui dev turned me onto the Swagger page. Very much a newbie here. Also, as you noticed I used your code to make this happen. How would you like me to attribute you?

**Comment by ghost** [comment]
You're fine -- I'm more surprised it works! hahah

**Comment by jonp92** [comment]
It was the easiest code ever to drop in since Anvil runs full Python.
